#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1620848629                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.tribu.default                                          # Enter Google Play Store URL.
presskit_download_link                    : # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover Tribu, the open-source mobile application that brings people together in private groups, allowing you to hang out with the people who matter most, whether it's your family, friends, or colleagues. Say goodbye to complicated account creation processes because Tribu makes it easy to join and connect instantly.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Adrien Peslerbe                                
your_link                                 : 
your_city                                 :                                 
email_address                             : adrien@pesler.be
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : PapyElGringo
github_username                           : PapyElGringo
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Private groups
    description                           : Create new tribes and share invitation links for others to join
    fontawesome_icon_name                 : people-group
    
  - title                                 : Chat
    description                           : Engage in lively discussions with exclusive chat for tribe members
    fontawesome_icon_name                 : comments

  - title                                 : Event planner
    description                           : Effortlessly plan and organize meetups with Tribu.
    fontawesome_icon_name                 : champagne-glasses

  - title                                 : Find the perfect date
    description                           : For Punctual and Stay Events, propose multiple dates and let tribe members vote for the best option. 
    fontawesome_icon_name                 : plane-departure

  - title                                 : Coordinate seamlessly with collaboration lists
    description                           : To-do Lists, Task Lists, Shopping Lists, IDea Listes, Customizable Shared Lists
    fontawesome_icon_name                 : list
  
  - title                                 : Expense Manager with Automatic Balancing
    description                           : Track expenses and automatically balance fees among participants
    fontawesome_icon_name                 : scale-balanced

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#003e51"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffb25f"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
